### ISSUE TITLE
Unhandled exception executing command 'invest' in plugin Invest v1.1

### ISSUE THREAD

**Issue by maximeflament** [0ddlyoko/Invest#1]
Bonjour,

Merci pour ton plugin!

J'ai une erreur quand je veux créer un invest.

Je crée bien la région avec World Guard, ensuite je lance la commande pour créer un investissement, et voilà ce que ça me donne:
`[11:11:53] [Server thread/INFO]: SweeDown issued server command: /invest create 1 14400 50000 87500 invest
[11:11:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'invest' in plugin Invest v1.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-TacoSpigot-"95870a93"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [server.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [server.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
	at me.oddlyoko.invest.libs.WorldGuardManager.loadRegion(WorldGuardManager.java:68) ~[?:?]
	at me.oddlyoko.invest.invest.InvestManager.createInvest(InvestManager.java:378) ~[?:?]
	at me.oddlyoko.invest.CommandInvest.onCommand(CommandInvest.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-TacoSpigot-"95870a93"]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-TacoSpigot-"95870a93"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at me.oddlyoko.invest.libs.WorldGuardManager.loadRegion(WorldGuardManager.java:68) ~[?:?]
	at me.oddlyoko.invest.invest.InvestManager.createInvest(InvestManager.java:378) ~[?:?]
	at me.oddlyoko.invest.CommandInvest.onCommand(CommandInvest.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-TacoSpigot-"95870a93"]
	... 15 more`

Plus d'infos sur mon serveur :

Version Spigot : TacoSpigot 1.8.8
Version WorldGuard : 6.1
Version Invest : 1.1

Je pense qu'il y a un conflit de versions!

**Comment by 0ddlyoko** [comment]
Bonsoir, désolé du retard je viens juste de voir cette erreur,
Le plugin est compatible avec WorldGuard 7.x et pas 6.x, je vais quand même essayer de patch cette erreur

**Comment by 0ddlyoko** [comment]
Heyy me revoila, j'ai mis à jour le plugin, peux-tu le tester en utilisant la dernière version (1.11) pour voir si le problème est réglé ?
( https://www.spigotmc.org/resources/invest.69528/ )

**Comment by 0ddlyoko** [comment]
Pas de réponse depuis plus de 9 mois, je considère que le problème est réglé.
Si ça ne l'est pas, veuillez ouvrir un nouveau ticket
